// Generated by scripts/build-model-manifest.ts — do not edit by hand.
// Run `npm run models:manifest` after adding or removing a .glb.

/** Every product mesh present in `public/models`, by public path. */
export const AVAILABLE_MODELS: ReadonlySet<string> = new Set([
  "/models/down-puffer-jacket-black.glb",
  "/models/owners-club-cap-black.glb",
  "/models/owners-club-hoodie-cobalt.glb",
  "/models/varsity-jacket-black-cream.glb",
]);
