/**
 * Scans `public/models` and writes the manifest the storefront reads.
 *
 * The browser cannot ask the filesystem whether a mesh exists, and probing with
 * a request per card would be worse than useless. So the list is baked at build
 * time: drop a .glb in, run `npm run models:manifest`, and the 3D affordance
 * appears for exactly the colourways that have one.
 */
import { existsSync, readdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";

import { seedProducts } from "../supabase/seed/catalog";
import { productModelPath } from "../src/lib/utils/product-models";

const modelDir = join(process.cwd(), "public", "models");
const outFile = join(
  process.cwd(),
  "src",
  "features",
  "products",
  "services",
  "utils",
  "available-models.ts",
);

const files = existsSync(modelDir)
  ? readdirSync(modelDir).filter((name) => name.endsWith(".glb")).sort()
  : [];

// Every mesh must belong to a real product/colour pair, or it is dead weight
// that will never be shown.
const known = new Set<string>();
for (const product of seedProducts) {
  for (const color of product.colors) {
    known.add(productModelPath(product.slug, color.name));
  }
}

const paths = files.map((file) => `/models/${file}`);
const orphans = paths.filter((path) => !known.has(path));

if (orphans.length) {
  console.error(`These meshes match no product/colour pair:`);
  orphans.forEach((path) => console.error("  " + path));
  process.exit(1);
}

const body = `// Generated by scripts/build-model-manifest.ts — do not edit by hand.
// Run \`npm run models:manifest\` after adding or removing a .glb.

/** Every product mesh present in \`public/models\`, by public path. */
export const AVAILABLE_MODELS: ReadonlySet<string> = new Set([
${paths.map((path) => `  "${path}",`).join("\n")}
]);
`;

writeFileSync(outFile, body, "utf8");
console.log(
  `wrote ${paths.length} mesh${paths.length === 1 ? "" : "es"} to available-models.ts`,
);
paths.forEach((path) => console.log("  " + path));
